version: '3.9'
services:
  postgres:
    image: quay.io/debezium/example-postgres:3.2
    container_name: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - ./config-postgres/ai-sample-data.sql:/docker-entrypoint-initdb.d/ai-sample-data.sql
  milvus:
    image: milvusdb/milvus:v2.5.4
    container_name: milvus
    environment:
      - ETCD_USE_EMBED=true
      - COMMON_STORAGETYPE=local
    ports:
      - "19530:19530"
      - "9091:9091"
    command: ["milvus", "run", "standalone"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091/healthz"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    depends_on:
      - milvus
      - postgres
  debezium-server:
    image: quay.io/debezium/server:3.2.0.Alpha1-ollama
    build:
      context: ./image-server
    container_name: debezium-server
    ports:
      - "8080:8080"
    volumes:
      - ./config-server:/debezium/config
    depends_on:
      milvus:
        condition: service_healthy
      postgres:
        condition: service_started
