name: Build [cloudevents]

on:
  push:
    paths:
      - 'cloudevents/**'
      - '.github/workflows/cloudevents-workflow.yml'
  pull_request:
    paths:
      - 'cloudevents/**'
      - '.github/workflows/cloudevents-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('cloudevents/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check changes in [cloudevents] example
        run: cd cloudevents && mvn clean install -f avro-data-extractor/pom.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
