name: Build [kstreams-fk-join]

on:
  push:
    paths:
      - 'kstreams-fk-join/**'
      - '.github/workflows/kstreams-fk-join-workflow.yml'
  pull_request:
    paths:
      - 'kstreams-fk-join/**'
      - '.github/workflows/kstreams-fk-join-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('kstreams-fk-join/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check changes in [kstreams-fk-join] example
        run: cd kstreams-fk-join && mvn clean verify -f aggregator/pom.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
